template-arb-file: app_es.arb
arb-dir: lib/localization
output-dir: lib/localization
output-localization-file: appwrite_auth_localizations.dart
output-class: AppwriteAuthLocalizations
preferred-supported-locales: [es]
use-deferred-loading: false
synthetic-package: false
nullable-getters: true
